.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. moselbit_qt test_moselbit_qt
clean: FORCE
	$(MAKE) -C .. moselbit_qt_clean test_moselbit_qt_clean
check: FORCE
	$(MAKE) -C .. test_moselbit_qt_check
moselbit-qt moselbit-qt.exe: FORCE
	 $(MAKE) -C .. moselbit_qt
